name: Faded
main: me.lilfade.faded.Faded
version: 0.08.02
description: >
             Faded plugin provides custom features on the game server
author: lilfade

commands:
  bug:
    description: report a bug
  suggestion:
    description: add a suggestion
  bv:
    description: display bukkit version for debug
  pm:
    description: sent private message to player